### ISSUE TITLE
Add context to records

### ISSUE THREAD

**Issue by sagikazarmark** [jeromegamez/php-psr-testlogger#3]
It might be useful to check if a specific value is added to the context or not. Common log handlers allow to pass the context as an array as well, not just appended to the log message.

**Comment by jeromegamez** [comment]
@sagikazarmark I just released [version 2.0.0](https://github.com/jeromegamez/php-psr-testlogger/releases/tag/2.0.0) which should enable you to check for anything your heart desires 🎉 - in case something is broken, please let me know!
